Treecollecting
ionide/FSharp.Analyzers.SDK pull request #140
Opened 2023-10-31 16:20 UTC by dawedawe

This adds infrastructure to process the AST and TAST in a hopefully easier way for analyzer authors.

2023-10-31 17:02 UTC, nojaf reviewed
Good stuff! I did some nit-picking from afar. Will review properly later this week!

2023-10-31 17:02 UTC, nojaf commented on src/FSharp.Analyzers.SDK/ASTCollecting.fsi
> +#nowarn "1182"
Can probably be dropped in the signature file.

2023-10-31 17:02 UTC, nojaf commented on src/FSharp.Analyzers.SDK/ASTCollecting.fsi
> +    val (|AllAttrs|): attrs: SynAttributes -> SynAttribute list
Should these active patterns be exposed?

2023-10-31 17:02 UTC, nojaf commented on src/FSharp.Analyzers.SDK/ASTCollecting.fsi
> +    type SyntaxCollectorBase =
This missing some good API documentation.
Perhaps even a `*.fsx` page for the docs to showcase the usage.

2023-11-02 08:28 UTC, dawedawe commented on src/FSharp.Analyzers.SDK/TASTCollecting.fs
> +    type TypedTreeCollectorBase() =
Yes, I ported all GR analyzers and all tests still pass.

2023-11-02 08:35 UTC, nojaf commented on src/FSharp.Analyzers.SDK/TASTCollecting.fs
> +    type TypedTreeCollectorBase() =
Great!

2023-11-02 16:47 UTC, nojaf requested changes
Good stuff!

2023-11-02 16:47 UTC, nojaf commented on docs/content/Dual Analyzer.fsx
> +The `allOpenStatements` function from above, rewritten to make use of `walkAst`, could look like this:
I would not show the old code in the first place.
Just straightly go with the new code and explain where these Collecting types are coming from.

2023-11-02 16:47 UTC, nojaf commented on docs/content/Dual Analyzer.fsx
> +For both trees, a type is defined, `SyntaxCollectorBase` and `TypedTreeCollectorBase` respectively, with members you can override to have easy access to the tree elements you want to process.
Add links to API docs: http://localhost:8901/reference/fsharp-analyzers-sdk-astcollecting-syntaxcollectorbase.html

2023-11-03 08:38 UTC, nojaf approved these changes

2023-11-03 09:21 UTC, merged