Unittesting docs
ionide/FSharp.Analyzers.SDK pull request #98
Opened 2023-09-20 09:44 UTC by dawedawe

2023-09-20 13:49 UTC, nojaf requested changes
Good stuff here.
A couple of nits left.

2023-09-20 13:49 UTC, nojaf commented on docs/content/Unit Testing.fsx
> +`FSharp.Analyzers.SDK.Testing.mkOptionsFromProject` creates the `FSharpProjectOptions` for the given framework (e.g. `net7.0`) and the given list of packages to reference.
Use more links for functions and types:
- http://localhost:8901/reference/fsharp-analyzers-sdk-testing.html (make relative URL)
- https://fsharp.github.io/fsharp-compiler-docs/reference/fsharp-compiler-codeanalysis-fsharpprojectoptions.html

2023-09-20 13:49 UTC, nojaf commented on docs/content/Unit Testing.fsx
> +                    {
Maybe add a comment that says it is going to be used in the `dotnet add package x --version y` style.
Nit: I would only add the json example. One item in the list makes it clear what this does.

2023-09-20 13:49 UTC, nojaf commented on docs/content/Unit Testing.fsx
> +The module `FSharp.Analyzers.SDK.Testing.Assert` offers various functions to help with assertion statements from your favorite unit testing framework.
Link here as well.

2023-09-20 16:12 UTC, dawedawe commented
> Good stuff here. A couple of nits left.

Thanks, really good suggestions.

2023-09-21 06:17 UTC, nojaf approved these changes

2023-09-21 06:24 UTC, merged